# Generated by Django 4.2.27 on 2025-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_analyzer_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
