# Generated by Django 6.0 on 2026-01-05 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_analyzer_app', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/%Y/%m/%d/')),
                ('predicted_class', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField()),
                ('heatmap', models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
